server:
  port: 8090

spring:
  application:
    name: bank-warning-server
  datasource:
    url: ${BANK_DB_URL:jdbc:postgresql://localhost:5432/bank_risk_db}
    username: ${BANK_DB_USERNAME:postgres}
    password: ${BANK_DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver

app:
  model-service:
    base-url: http://localhost:8088
    default-model-api: /v0/mi/risk-level
    connect-timeout: 5s
    read-timeout: 600s
